version: "3"

services:

  nginx:
    image: nginx:latest
    depends_on:
      - wp
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - frontend
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d:ro
      - ${PWD}/wp:/var/www/html:ro

  specify7:
    build: ./specify7
    depends_on:
      - mariadb
    ports:
      - "80:80"
    networks:
      - backend_sp7
      - frontend
    volumes:
      - ./specify7/specify6_thick_client:/usr/local/specify6
      - ./specify7/specify7_config:/usr/local/specify_config
      - ~/.specify7-docker/data/specify7/specify_wb_upload:/usr/local/specify_wb_upload
      - ~/.specify7-docker/data/specify7/specify_depository:/var/www/html/specify/specify_depository

  wp:
    image: ./wp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: specify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - frontend
      - backend-wp
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: specify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - backend-sp7
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  jre:
    image: amazoncorretto:8
    networks:
      - backend-wp
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

networks:
  frontend:
    driver: bridge
  backend-sp7:
    driver: bridge
  backend-wp:
    driver: bridge